#!/bin/bash
jupyter trust inv-limits-interface.ipynb
# jupyter nbconvert inv-limits-interface.ipynb --TagRemovePreprocessor.remove_input_tags='{"hide-input"}' --to=notebook --inplace
# jupyter nbconvert inv-limits-interface.ipynb --template=nextensions --to=notebook --inplace
# jupyter nbconvert --to notebook --execute inv-limits-interface.ipynb
