#!/bin/bash
# jupyter nbconvert inv-limits-interface.ipynb --TagRemovePreprocessor.remove_input_tags='{"hide-input"}' --to=notebook --inplace
jupyter nbconvert inv-limits-interface.ipynb --template=nextensions --to=notebook --inplace
